# Generated by Django 5.1.6 on 2025-03-13 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Forum Categories'},
        ),
        migrations.AlterModelOptions(
            name='forumcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='slug',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(default='fas fa-folder', help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('P', 'Programcı'), ('M', 'Mühendis'), ('D', 'Diğer')], default='P', max_length=1)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('skills', models.ManyToManyField(blank=True, to='app.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
